path_CTSM_source = "/glade/u/home/guoqiang/CTSM_repos/CTSM"
path_CTSM_case = "/glade/work/guoqiang/CTSM_cases/CAMELS_Calib/Lump_calib/CAMELS_10"
path_CTSM_CIMEout = "/glade/scratch/guoqiang/CTSM_outputs/CAMELS_Calib/Lump_calib/CAMELS_10"
file_CTSM_mesh = "/glade/work/guoqiang/CTSM_cases/CAMELS_Calib/Lump_basin_mask/ESMFmesh_ctsm_HCDN_nhru_final_671_v0_8e-3_basin{bnum}.nc"
file_CTSM_surfdata = "/glade/work/guoqiang/CTSM_cases/CAMELS_Calib/shared_data_Sean/surfdata_CAMELS_hist_78pfts_CMIP6_simyr2000_c221004.nc"
RUN_STARTDATE = "2000-01-01"
STOP_N = 36
STOP_OPTION = "nmonths"
NTASKS = 1
casebuild = "direct"
projectCode = "P08010000"
